vote_result.calculated_field:
  type: mapping
  mapping:
    field_name:
      label: 'Field name'
      type: string
    result_function:
      label: 'Result function'
      type: string

vote_result.vote_res_type.*:
  type: config_entity
  label: 'Vote result type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    fields:
      label: 'Fields'
      type: sequence
      sequence:
        type: vote_result.calculated_field
    uuid:
      type: string
