<?php

/**
 * @file
 * Contains admin_toolbar_ext.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function admin_toolbar_ext_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the admin_toolbar_ext module.
    case 'help.page.admin_toolbar_ext':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Admin Toolbar extension') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 *
 * @see template_preprocess_maintenance_page()
 * @see \Drupal\Core\EventSubscriber\ActiveLinkResponseFilter
 */
function admin_toolbar_ext_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'admin_toolbar_ext/admin_toolbar_ext';
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function admin_toolbar_ext_preprocess_menu__toolbar__admin(&$variables) {
  _admin_toolbar_ext_menu_add_level_class($variables['items']);
}

function _admin_toolbar_ext_menu_add_level_class(array $items, $level = 0) {

  foreach (array_values($items) as $key => $item) {
    /** @var \Drupal\Core\Template\Attribute $attributes */
    $attributes = $item['attributes'];

    $attributes->addClass('menu-level-' . $level);

    if (!empty($item['below'])) {
      _admin_toolbar_ext_menu_add_level_class($item['below'], $level + 1);
    }
  }
}
