message_group_notify.message_group_type.*:
  type: config_entity
  label: 'Message group type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
